kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: foo
    workload: ingress-demo
spec:
  containers:
  - name: foo-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text='hello world! this is foo'"
---
kind: Service
apiVersion: v1
metadata:
  name: foo-service
  labels:
    workload: ingress-demo
spec:
  selector:
    app: foo
  ports:
  # Default port used by the image
  - port: 5678
---
kind: Pod
apiVersion: v1
metadata:
  name: bar-app
  labels:
    app: bar
    workload: ingress-demo
spec:
  containers:
  - name: bar-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text='hello world! this is bar'"
---
kind: Service
apiVersion: v1
metadata:
  name: bar-service
  labels:
    workload: ingress-demo
spec:
  selector:
    app: bar
  ports:
  # Default port used by the image
  - port: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  labels:
    workload: ingress-demo
spec:
  rules:
  - http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: foo-service
            port:
              number: 5678
      - path: /bar
        pathType: Prefix
        backend:
          service:
            name: bar-service
            port:
              number: 5678
---
